### ISSUE TITLE
Тут тоже надо лицензию вставить.

### ISSUE THREAD

**Issue by mirotvorec85** [smartholdem/smartholdem-rpc#4]
https://github.com/smartholdem/smartholdem-rpc/blob/a9d1302282a2aff977f3d4494a86c3375b979821/LICENSE#L3

**Comment by backmeupplz** [comment]
На самом деле, вам бы рабочий сервис людям предоставить, а не о лицензиях думать. Ничего ведь так и не запустили, чем кто-либо бы пользовался :)
